name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the hello Docker image
      run: docker build apps/hello -t app-hello:$(date +%s)
    - name: Build the World Docker image
      run: docker build apps/world -t app-world:$(date +%s)
