name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: actions/checkout@v2
    - name: Build the hello Docker image
      run: |
        docker build apps/hello -t ghcr.io/ch-yassine18/app-hello:latest
        docker push ghcr.io/ch-yassine18/app-hello:latest
      
    - name: Build the World Docker image
      run: |
        docker build apps/world -t ghcr.io/ch-yassine18/app-world:latest
        docker push ghcr.io/ch-yassine18/app-world:latest
    
      
   

